FROM stacks2 as stacks2-test
COPY tests/test_samples/ /test_samples/
COPY tests/popmap_test /
COPY tests/run_test.sh /
COPY tests/expected_best_params.txt /

RUN chmod +x run_test.sh

CMD ["./run_test.sh"]
